# Generated by Django 5.0.4 on 2024-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='code',
        ),
        migrations.AlterField(
            model_name='record',
            name='codehex',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
    ]
